spring:
  application:
    name: jms-db
  jms:
    listener:
      max-concurrency: 16
      receive-timeout: 60000 # in ms!!!
      concurrency: 16
    cache:
      session-cache-size: 256
      consumers: false
      producers: true
      enabled: true


  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create
  datasource:
    hikari:
      auto-commit: false
      password: test
      username: test
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1

ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(1414)
    user: admin
    password: passw0rd
    pool:
      enabled: false
#      max-connections: 4
#      max-sessions-per-connection: 500


management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus