spring:
  application:
    name: jms-db
  jms:
    listener:
      max-concurrency: 1
      receive-timeout: 60000 # in ms!!!
      concurrency: 1
    cache:
      session-cache-size: 256
      consumers: false
      producers: true
      enabled: true

  jpa:
    #database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create
    open-in-view: false
  datasource:
    hikari:
      auto-commit: false
      password: cscs
      username: cscs
      minimum-idle: 10
      maximum-pool-size: 60
      idle-timeout: 60000

    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1

ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(1414)
    user: admin
    password: passw0rd
#    pool:
#      enabled: false
#      max-connections: 4
#      max-sessions-per-connection: 500


management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus


logging:
  level:
    org:
      springframework:
        jms: TRACE
        transaction:
          interceptor: TRACE
      hibernate:
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG
    com:
      zaxxer:
        hikari: TRACE